"""
✨ `CompCard_KeyOutput` returns the primary key fields of table type `CompCard`.

It has the same format as `CompCard_Key`, but is only used as mutation return value.
"""
scalar CompCard_KeyOutput
"""
✨ `Image_KeyOutput` returns the primary key fields of table type `Image`.

It has the same format as `Image_Key`, but is only used as mutation return value.
"""
scalar Image_KeyOutput
"""
✨ `Portfolio_KeyOutput` returns the primary key fields of table type `Portfolio`.

It has the same format as `Portfolio_Key`, but is only used as mutation return value.
"""
scalar Portfolio_KeyOutput
"""
✨ `Profile_KeyOutput` returns the primary key fields of table type `Profile`.

It has the same format as `Profile_Key`, but is only used as mutation return value.
"""
scalar Profile_KeyOutput
"""
✨ `Shoot_KeyOutput` returns the primary key fields of table type `Shoot`.

It has the same format as `Shoot_Key`, but is only used as mutation return value.
"""
scalar Shoot_KeyOutput
"""
✨ `ShootImage_KeyOutput` returns the primary key fields of table type `ShootImage`.

It has the same format as `ShootImage_Key`, but is only used as mutation return value.
"""
scalar ShootImage_KeyOutput
"""
✨ `User_KeyOutput` returns the primary key fields of table type `User`.

It has the same format as `User_Key`, but is only used as mutation return value.
"""
scalar User_KeyOutput
"""
✨ Generated data input type for table 'CompCard'. It includes all necessary fields for creating or upserting rows into table.
"""
input CompCard_Data {
  """
  ✨ Generated from Field `CompCard`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `CompCard`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `CompCard`.`userUid` of type `String!`
  """
  userUid: String
  """
  ✨ `_expr` server value variant of `userUid` (✨ Generated from Field `CompCard`.`userUid` of type `String!`)
  """
  userUid_expr: String_Expr
  """
  ✨ Generated from Field `CompCard`.`user` of type `User!`
  """
  user: User_Key
  """
  ✨ Generated from Field `CompCard`.`aesthetic` of type `String!`
  """
  aesthetic: String
  """
  ✨ `_expr` server value variant of `aesthetic` (✨ Generated from Field `CompCard`.`aesthetic` of type `String!`)
  """
  aesthetic_expr: String_Expr
  """
  ✨ Generated from Field `CompCard`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `CompCard`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `CompCard`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `CompCard`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `CompCard`.`layout` of type `String!`
  """
  layout: String
  """
  ✨ `_expr` server value variant of `layout` (✨ Generated from Field `CompCard`.`layout` of type `String!`)
  """
  layout_expr: String_Expr
  """
  ✨ Generated from Field `CompCard`.`profileSnapshot` of type `String`
  """
  profileSnapshot: String
  """
  ✨ `_expr` server value variant of `profileSnapshot` (✨ Generated from Field `CompCard`.`profileSnapshot` of type `String`)
  """
  profileSnapshot_expr: String_Expr
  """
  ✨ Generated from Field `CompCard`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `CompCard`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `CompCard`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `CompCard`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_update: [Timestamp_Update!]
}
"""
✨ Generated filter input type for table 'CompCard'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input CompCard_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [CompCard_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: CompCard_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [CompCard_Filter!]
  """
  ✨ Generated from Field `CompCard`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `CompCard`.`userUid` of type `String!`
  """
  userUid: String_Filter
  """
  ✨ Generated from Field `CompCard`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `CompCard`.`aesthetic` of type `String!`
  """
  aesthetic: String_Filter
  """
  ✨ Generated from Field `CompCard`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `CompCard`.`layout` of type `String!`
  """
  layout: String_Filter
  """
  ✨ Generated from Field `CompCard`.`profileSnapshot` of type `String`
  """
  profileSnapshot: String_Filter
  """
  ✨ Generated from Field `CompCard`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
}
"""
✨ Generated first-row input type for table 'CompCard'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input CompCard_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [CompCard_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: CompCard_Filter
}
"""
✨ Generated having input type for table 'CompCard'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input CompCard_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [CompCard_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: CompCard_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [CompCard_Having!]
  """
  ✨ Generated from Field `CompCard`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `CompCard`.`aesthetic_count` of type `Int!`
  """
  aesthetic_count: Int_Filter
  """
  ✨ Generated from Field `CompCard`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `CompCard`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `CompCard`.`layout_count` of type `Int!`
  """
  layout_count: Int_Filter
  """
  ✨ Generated from Field `CompCard`.`profileSnapshot_count` of type `Int!`
  """
  profileSnapshot_count: Int_Filter
  """
  ✨ Generated from Field `CompCard`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `CompCard`.`userUid_count` of type `Int!`
  """
  userUid_count: Int_Filter
  """
  ✨ Generated from Field `CompCard`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `CompCard`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `CompCard`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `CompCard`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'CompCard'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input CompCard_Key {
  """
  ✨ Generated from Field `CompCard`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `CompCard`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'CompCard'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input CompCard_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: CompCard_Filter
}
"""
✨ Generated order input type for table 'CompCard'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input CompCard_Order {
  """
  ✨ Generated from Field `CompCard`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`userUid` of type `String!`
  """
  userUid: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `CompCard`.`aesthetic` of type `String!`
  """
  aesthetic: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`layout` of type `String!`
  """
  layout: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`profileSnapshot` of type `String`
  """
  profileSnapshot: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`aesthetic_count` of type `Int!`
  """
  aesthetic_count: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`layout_count` of type `Int!`
  """
  layout_count: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`profileSnapshot_count` of type `Int!`
  """
  profileSnapshot_count: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`userUid_count` of type `Int!`
  """
  userUid_count: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `CompCard`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Image'. It includes all necessary fields for creating or upserting rows into table.
"""
input Image_Data {
  """
  ✨ Generated from Field `Image`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Image`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Image`.`userUid` of type `String!`
  """
  userUid: String
  """
  ✨ `_expr` server value variant of `userUid` (✨ Generated from Field `Image`.`userUid` of type `String!`)
  """
  userUid_expr: String_Expr
  """
  ✨ Generated from Field `Image`.`user` of type `User!`
  """
  user: User_Key
  """
  ✨ Generated from Field `Image`.`fileHash` of type `String`
  """
  fileHash: String
  """
  ✨ `_expr` server value variant of `fileHash` (✨ Generated from Field `Image`.`fileHash` of type `String`)
  """
  fileHash_expr: String_Expr
  """
  ✨ Generated from Field `Image`.`metadata` of type `String`
  """
  metadata: String
  """
  ✨ `_expr` server value variant of `metadata` (✨ Generated from Field `Image`.`metadata` of type `String`)
  """
  metadata_expr: String_Expr
  """
  ✨ Generated from Field `Image`.`uploadedAt` of type `Timestamp!`
  """
  uploadedAt: Timestamp
  """
  ✨ `_expr` server value variant of `uploadedAt` (✨ Generated from Field `Image`.`uploadedAt` of type `Timestamp!`)
  """
  uploadedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `uploadedAt` (✨ Generated from Field `Image`.`uploadedAt` of type `Timestamp!`)
  """
  uploadedAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `uploadedAt` (✨ Generated from Field `Image`.`uploadedAt` of type `Timestamp!`)
  """
  uploadedAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Image`.`url` of type `String!`
  """
  url: String
  """
  ✨ `_expr` server value variant of `url` (✨ Generated from Field `Image`.`url` of type `String!`)
  """
  url_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Image'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Image_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Image_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Image_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Image_Filter!]
  """
  ✨ Generated from Field `Image`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Image`.`userUid` of type `String!`
  """
  userUid: String_Filter
  """
  ✨ Generated from Field `Image`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Image`.`fileHash` of type `String`
  """
  fileHash: String_Filter
  """
  ✨ Generated from Field `Image`.`metadata` of type `String`
  """
  metadata: String_Filter
  """
  ✨ Generated from Field `Image`.`uploadedAt` of type `Timestamp!`
  """
  uploadedAt: Timestamp_Filter
  """
  ✨ Generated from Field `Image`.`url` of type `String!`
  """
  url: String_Filter
  """
  ✨ Generated from Field `Image`.`shootImages_on_image` of type `[ShootImage!]!`
  """
  shootImages_on_image: ShootImage_ListFilter
  """
  ✨ Generated from Field `Image`.`shoots_via_ShootImage` of type `[Shoot!]!`
  """
  shoots_via_ShootImage: Shoot_ListFilter
}
"""
✨ Generated first-row input type for table 'Image'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Image_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Image_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Image_Filter
}
"""
✨ Generated having input type for table 'Image'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Image_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Image_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Image_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Image_Having!]
  """
  ✨ Generated from Field `Image`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Image`.`fileHash_count` of type `Int!`
  """
  fileHash_count: Int_Filter
  """
  ✨ Generated from Field `Image`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Image`.`metadata_count` of type `Int!`
  """
  metadata_count: Int_Filter
  """
  ✨ Generated from Field `Image`.`uploadedAt_count` of type `Int!`
  """
  uploadedAt_count: Int_Filter
  """
  ✨ Generated from Field `Image`.`url_count` of type `Int!`
  """
  url_count: Int_Filter
  """
  ✨ Generated from Field `Image`.`userUid_count` of type `Int!`
  """
  userUid_count: Int_Filter
  """
  ✨ Generated from Field `Image`.`uploadedAt_min` of type `Timestamp`
  """
  uploadedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Image`.`uploadedAt_max` of type `Timestamp`
  """
  uploadedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Image'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Image_Key {
  """
  ✨ Generated from Field `Image`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Image`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Image'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Image_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Image_Filter
}
"""
✨ Generated order input type for table 'Image'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Image_Order {
  """
  ✨ Generated from Field `Image`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Image`.`userUid` of type `String!`
  """
  userUid: OrderDirection
  """
  ✨ Generated from Field `Image`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Image`.`fileHash` of type `String`
  """
  fileHash: OrderDirection
  """
  ✨ Generated from Field `Image`.`metadata` of type `String`
  """
  metadata: OrderDirection
  """
  ✨ Generated from Field `Image`.`uploadedAt` of type `Timestamp!`
  """
  uploadedAt: OrderDirection
  """
  ✨ Generated from Field `Image`.`url` of type `String!`
  """
  url: OrderDirection
  """
  ✨ Generated from Field `Image`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Image`.`fileHash_count` of type `Int!`
  """
  fileHash_count: OrderDirection
  """
  ✨ Generated from Field `Image`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Image`.`metadata_count` of type `Int!`
  """
  metadata_count: OrderDirection
  """
  ✨ Generated from Field `Image`.`uploadedAt_count` of type `Int!`
  """
  uploadedAt_count: OrderDirection
  """
  ✨ Generated from Field `Image`.`url_count` of type `Int!`
  """
  url_count: OrderDirection
  """
  ✨ Generated from Field `Image`.`userUid_count` of type `Int!`
  """
  userUid_count: OrderDirection
  """
  ✨ Generated from Field `Image`.`uploadedAt_min` of type `Timestamp`
  """
  uploadedAt_min: OrderDirection
  """
  ✨ Generated from Field `Image`.`uploadedAt_max` of type `Timestamp`
  """
  uploadedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Portfolio'. It includes all necessary fields for creating or upserting rows into table.
"""
input Portfolio_Data {
  """
  ✨ Generated from Field `Portfolio`.`userUid` of type `String!`
  """
  userUid: String
  """
  ✨ `_expr` server value variant of `userUid` (✨ Generated from Field `Portfolio`.`userUid` of type `String!`)
  """
  userUid_expr: String_Expr
  """
  ✨ Generated from Field `Portfolio`.`user` of type `User!`
  """
  user: User_Key
  """
  ✨ Generated from Field `Portfolio`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Portfolio`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Portfolio`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Portfolio`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Portfolio`.`isPublic` of type `Boolean!`
  """
  isPublic: Boolean
  """
  ✨ `_expr` server value variant of `isPublic` (✨ Generated from Field `Portfolio`.`isPublic` of type `Boolean!`)
  """
  isPublic_expr: Boolean_Expr
  """
  ✨ Generated from Field `Portfolio`.`settings` of type `String`
  """
  settings: String
  """
  ✨ `_expr` server value variant of `settings` (✨ Generated from Field `Portfolio`.`settings` of type `String`)
  """
  settings_expr: String_Expr
  """
  ✨ Generated from Field `Portfolio`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `Portfolio`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `Portfolio`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `Portfolio`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_update: [Timestamp_Update!]
}
"""
✨ Generated filter input type for table 'Portfolio'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Portfolio_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Portfolio_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Portfolio_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Portfolio_Filter!]
  """
  ✨ Generated from Field `Portfolio`.`userUid` of type `String!`
  """
  userUid: String_Filter
  """
  ✨ Generated from Field `Portfolio`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Portfolio`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Portfolio`.`isPublic` of type `Boolean!`
  """
  isPublic: Boolean_Filter
  """
  ✨ Generated from Field `Portfolio`.`settings` of type `String`
  """
  settings: String_Filter
  """
  ✨ Generated from Field `Portfolio`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `Portfolio`.`shoots_on_portfolio` of type `[Shoot!]!`
  """
  shoots_on_portfolio: Shoot_ListFilter
}
"""
✨ Generated first-row input type for table 'Portfolio'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Portfolio_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Portfolio_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Portfolio_Filter
}
"""
✨ Generated having input type for table 'Portfolio'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Portfolio_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Portfolio_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Portfolio_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Portfolio_Having!]
  """
  ✨ Generated from Field `Portfolio`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Portfolio`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Portfolio`.`isPublic_count` of type `Int!`
  """
  isPublic_count: Int_Filter
  """
  ✨ Generated from Field `Portfolio`.`settings_count` of type `Int!`
  """
  settings_count: Int_Filter
  """
  ✨ Generated from Field `Portfolio`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `Portfolio`.`userUid_count` of type `Int!`
  """
  userUid_count: Int_Filter
  """
  ✨ Generated from Field `Portfolio`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Portfolio`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Portfolio`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Portfolio`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Portfolio'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Portfolio_Key {
  """
  ✨ Generated from Field `Portfolio`.`userUid` of type `String!`
  """
  userUid: String
  """
  ✨ `_expr` server value variant of `userUid` (✨ Generated from Field `Portfolio`.`userUid` of type `String!`)
  """
  userUid_expr: String_Expr
}
"""
✨ Generated list filter input type for table 'Portfolio'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Portfolio_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Portfolio_Filter
}
"""
✨ Generated order input type for table 'Portfolio'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Portfolio_Order {
  """
  ✨ Generated from Field `Portfolio`.`userUid` of type `String!`
  """
  userUid: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Portfolio`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`isPublic` of type `Boolean!`
  """
  isPublic: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`settings` of type `String`
  """
  settings: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`isPublic_count` of type `Int!`
  """
  isPublic_count: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`settings_count` of type `Int!`
  """
  settings_count: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`userUid_count` of type `Int!`
  """
  userUid_count: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Portfolio`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Profile'. It includes all necessary fields for creating or upserting rows into table.
"""
input Profile_Data {
  """
  ✨ Generated from Field `Profile`.`userUid` of type `String!`
  """
  userUid: String
  """
  ✨ `_expr` server value variant of `userUid` (✨ Generated from Field `Profile`.`userUid` of type `String!`)
  """
  userUid_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`user` of type `User!`
  """
  user: User_Key
  """
  ✨ Generated from Field `Profile`.`avatar` of type `String`
  """
  avatar: String
  """
  ✨ `_expr` server value variant of `avatar` (✨ Generated from Field `Profile`.`avatar` of type `String`)
  """
  avatar_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`bust` of type `String!`
  """
  bust: String
  """
  ✨ `_expr` server value variant of `bust` (✨ Generated from Field `Profile`.`bust` of type `String!`)
  """
  bust_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`careerGoals` of type `String`
  """
  careerGoals: String
  """
  ✨ `_expr` server value variant of `careerGoals` (✨ Generated from Field `Profile`.`careerGoals` of type `String`)
  """
  careerGoals_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Profile`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`dressSize` of type `String!`
  """
  dressSize: String
  """
  ✨ `_expr` server value variant of `dressSize` (✨ Generated from Field `Profile`.`dressSize` of type `String!`)
  """
  dressSize_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`eyeColor` of type `String!`
  """
  eyeColor: String
  """
  ✨ `_expr` server value variant of `eyeColor` (✨ Generated from Field `Profile`.`eyeColor` of type `String!`)
  """
  eyeColor_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`hairColor` of type `String!`
  """
  hairColor: String
  """
  ✨ `_expr` server value variant of `hairColor` (✨ Generated from Field `Profile`.`hairColor` of type `String!`)
  """
  hairColor_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`height` of type `String!`
  """
  height: String
  """
  ✨ `_expr` server value variant of `height` (✨ Generated from Field `Profile`.`height` of type `String!`)
  """
  height_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`hips` of type `String!`
  """
  hips: String
  """
  ✨ `_expr` server value variant of `hips` (✨ Generated from Field `Profile`.`hips` of type `String!`)
  """
  hips_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`instagram` of type `String`
  """
  instagram: String
  """
  ✨ `_expr` server value variant of `instagram` (✨ Generated from Field `Profile`.`instagram` of type `String`)
  """
  instagram_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Profile`.`name` of type `String!`)
  """
  name_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`shoeSize` of type `String!`
  """
  shoeSize: String
  """
  ✨ `_expr` server value variant of `shoeSize` (✨ Generated from Field `Profile`.`shoeSize` of type `String!`)
  """
  shoeSize_expr: String_Expr
  """
  ✨ Generated from Field `Profile`.`waist` of type `String!`
  """
  waist: String
  """
  ✨ `_expr` server value variant of `waist` (✨ Generated from Field `Profile`.`waist` of type `String!`)
  """
  waist_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Profile'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Profile_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Profile_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Profile_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Profile_Filter!]
  """
  ✨ Generated from Field `Profile`.`userUid` of type `String!`
  """
  userUid: String_Filter
  """
  ✨ Generated from Field `Profile`.`user` of type `User!`
  """
  user: User_Filter
  """
  ✨ Generated from Field `Profile`.`avatar` of type `String`
  """
  avatar: String_Filter
  """
  ✨ Generated from Field `Profile`.`bust` of type `String!`
  """
  bust: String_Filter
  """
  ✨ Generated from Field `Profile`.`careerGoals` of type `String`
  """
  careerGoals: String_Filter
  """
  ✨ Generated from Field `Profile`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Profile`.`dressSize` of type `String!`
  """
  dressSize: String_Filter
  """
  ✨ Generated from Field `Profile`.`eyeColor` of type `String!`
  """
  eyeColor: String_Filter
  """
  ✨ Generated from Field `Profile`.`hairColor` of type `String!`
  """
  hairColor: String_Filter
  """
  ✨ Generated from Field `Profile`.`height` of type `String!`
  """
  height: String_Filter
  """
  ✨ Generated from Field `Profile`.`hips` of type `String!`
  """
  hips: String_Filter
  """
  ✨ Generated from Field `Profile`.`instagram` of type `String`
  """
  instagram: String_Filter
  """
  ✨ Generated from Field `Profile`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Profile`.`shoeSize` of type `String!`
  """
  shoeSize: String_Filter
  """
  ✨ Generated from Field `Profile`.`waist` of type `String!`
  """
  waist: String_Filter
}
"""
✨ Generated first-row input type for table 'Profile'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Profile_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Profile_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Profile_Filter
}
"""
✨ Generated having input type for table 'Profile'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Profile_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Profile_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Profile_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Profile_Having!]
  """
  ✨ Generated from Field `Profile`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`avatar_count` of type `Int!`
  """
  avatar_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`bust_count` of type `Int!`
  """
  bust_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`careerGoals_count` of type `Int!`
  """
  careerGoals_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`dressSize_count` of type `Int!`
  """
  dressSize_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`eyeColor_count` of type `Int!`
  """
  eyeColor_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`hairColor_count` of type `Int!`
  """
  hairColor_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`height_count` of type `Int!`
  """
  height_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`hips_count` of type `Int!`
  """
  hips_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`instagram_count` of type `Int!`
  """
  instagram_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`shoeSize_count` of type `Int!`
  """
  shoeSize_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`userUid_count` of type `Int!`
  """
  userUid_count: Int_Filter
  """
  ✨ Generated from Field `Profile`.`waist_count` of type `Int!`
  """
  waist_count: Int_Filter
}
"""
✨ Generated key input type for table 'Profile'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Profile_Key {
  """
  ✨ Generated from Field `Profile`.`userUid` of type `String!`
  """
  userUid: String
  """
  ✨ `_expr` server value variant of `userUid` (✨ Generated from Field `Profile`.`userUid` of type `String!`)
  """
  userUid_expr: String_Expr
}
"""
✨ Generated list filter input type for table 'Profile'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Profile_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Profile_Filter
}
"""
✨ Generated order input type for table 'Profile'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Profile_Order {
  """
  ✨ Generated from Field `Profile`.`userUid` of type `String!`
  """
  userUid: OrderDirection
  """
  ✨ Generated from Field `Profile`.`user` of type `User!`
  """
  user: User_Order
  """
  ✨ Generated from Field `Profile`.`avatar` of type `String`
  """
  avatar: OrderDirection
  """
  ✨ Generated from Field `Profile`.`bust` of type `String!`
  """
  bust: OrderDirection
  """
  ✨ Generated from Field `Profile`.`careerGoals` of type `String`
  """
  careerGoals: OrderDirection
  """
  ✨ Generated from Field `Profile`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Profile`.`dressSize` of type `String!`
  """
  dressSize: OrderDirection
  """
  ✨ Generated from Field `Profile`.`eyeColor` of type `String!`
  """
  eyeColor: OrderDirection
  """
  ✨ Generated from Field `Profile`.`hairColor` of type `String!`
  """
  hairColor: OrderDirection
  """
  ✨ Generated from Field `Profile`.`height` of type `String!`
  """
  height: OrderDirection
  """
  ✨ Generated from Field `Profile`.`hips` of type `String!`
  """
  hips: OrderDirection
  """
  ✨ Generated from Field `Profile`.`instagram` of type `String`
  """
  instagram: OrderDirection
  """
  ✨ Generated from Field `Profile`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Profile`.`shoeSize` of type `String!`
  """
  shoeSize: OrderDirection
  """
  ✨ Generated from Field `Profile`.`waist` of type `String!`
  """
  waist: OrderDirection
  """
  ✨ Generated from Field `Profile`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`avatar_count` of type `Int!`
  """
  avatar_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`bust_count` of type `Int!`
  """
  bust_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`careerGoals_count` of type `Int!`
  """
  careerGoals_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`dressSize_count` of type `Int!`
  """
  dressSize_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`eyeColor_count` of type `Int!`
  """
  eyeColor_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`hairColor_count` of type `Int!`
  """
  hairColor_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`height_count` of type `Int!`
  """
  height_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`hips_count` of type `Int!`
  """
  hips_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`instagram_count` of type `Int!`
  """
  instagram_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`shoeSize_count` of type `Int!`
  """
  shoeSize_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`userUid_count` of type `Int!`
  """
  userUid_count: OrderDirection
  """
  ✨ Generated from Field `Profile`.`waist_count` of type `Int!`
  """
  waist_count: OrderDirection
}
"""
✨ Generated data input type for table 'Shoot'. It includes all necessary fields for creating or upserting rows into table.
"""
input Shoot_Data {
  """
  ✨ Generated from Field `Shoot`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Shoot`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Shoot`.`portfolioUserUid` of type `String!`
  """
  portfolioUserUid: String
  """
  ✨ `_expr` server value variant of `portfolioUserUid` (✨ Generated from Field `Shoot`.`portfolioUserUid` of type `String!`)
  """
  portfolioUserUid_expr: String_Expr
  """
  ✨ Generated from Field `Shoot`.`portfolio` of type `Portfolio!`
  """
  portfolio: Portfolio_Key
  """
  ✨ Generated from Field `Shoot`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Shoot`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Shoot`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Shoot`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Shoot`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Shoot`.`name` of type `String!`)
  """
  name_expr: String_Expr
  """
  ✨ Generated from Field `Shoot`.`photographer` of type `String`
  """
  photographer: String
  """
  ✨ `_expr` server value variant of `photographer` (✨ Generated from Field `Shoot`.`photographer` of type `String`)
  """
  photographer_expr: String_Expr
  """
  ✨ Generated from Field `Shoot`.`studio` of type `String`
  """
  studio: String
  """
  ✨ `_expr` server value variant of `studio` (✨ Generated from Field `Shoot`.`studio` of type `String`)
  """
  studio_expr: String_Expr
  """
  ✨ Generated from Field `Shoot`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `Shoot`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `Shoot`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `Shoot`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Shoot`.`vibes` of type `String`
  """
  vibes: String
  """
  ✨ `_expr` server value variant of `vibes` (✨ Generated from Field `Shoot`.`vibes` of type `String`)
  """
  vibes_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Shoot'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Shoot_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Shoot_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Shoot_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Shoot_Filter!]
  """
  ✨ Generated from Field `Shoot`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Shoot`.`portfolioUserUid` of type `String!`
  """
  portfolioUserUid: String_Filter
  """
  ✨ Generated from Field `Shoot`.`portfolio` of type `Portfolio!`
  """
  portfolio: Portfolio_Filter
  """
  ✨ Generated from Field `Shoot`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Shoot`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Shoot`.`photographer` of type `String`
  """
  photographer: String_Filter
  """
  ✨ Generated from Field `Shoot`.`studio` of type `String`
  """
  studio: String_Filter
  """
  ✨ Generated from Field `Shoot`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `Shoot`.`vibes` of type `String`
  """
  vibes: String_Filter
  """
  ✨ Generated from Field `Shoot`.`shootImages_on_shoot` of type `[ShootImage!]!`
  """
  shootImages_on_shoot: ShootImage_ListFilter
  """
  ✨ Generated from Field `Shoot`.`images_via_ShootImage` of type `[Image!]!`
  """
  images_via_ShootImage: Image_ListFilter
}
"""
✨ Generated first-row input type for table 'Shoot'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Shoot_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Shoot_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Shoot_Filter
}
"""
✨ Generated having input type for table 'Shoot'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Shoot_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Shoot_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Shoot_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Shoot_Having!]
  """
  ✨ Generated from Field `Shoot`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Shoot`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Shoot`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Shoot`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Shoot`.`photographer_count` of type `Int!`
  """
  photographer_count: Int_Filter
  """
  ✨ Generated from Field `Shoot`.`portfolioUserUid_count` of type `Int!`
  """
  portfolioUserUid_count: Int_Filter
  """
  ✨ Generated from Field `Shoot`.`studio_count` of type `Int!`
  """
  studio_count: Int_Filter
  """
  ✨ Generated from Field `Shoot`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `Shoot`.`vibes_count` of type `Int!`
  """
  vibes_count: Int_Filter
  """
  ✨ Generated from Field `Shoot`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Shoot`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Shoot`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Shoot`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Shoot'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Shoot_Key {
  """
  ✨ Generated from Field `Shoot`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Shoot`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Shoot'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Shoot_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Shoot_Filter
}
"""
✨ Generated order input type for table 'Shoot'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Shoot_Order {
  """
  ✨ Generated from Field `Shoot`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`portfolioUserUid` of type `String!`
  """
  portfolioUserUid: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`portfolio` of type `Portfolio!`
  """
  portfolio: Portfolio_Order
  """
  ✨ Generated from Field `Shoot`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`photographer` of type `String`
  """
  photographer: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`studio` of type `String`
  """
  studio: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`vibes` of type `String`
  """
  vibes: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`photographer_count` of type `Int!`
  """
  photographer_count: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`portfolioUserUid_count` of type `Int!`
  """
  portfolioUserUid_count: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`studio_count` of type `Int!`
  """
  studio_count: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`vibes_count` of type `Int!`
  """
  vibes_count: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Shoot`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'ShootImage'. It includes all necessary fields for creating or upserting rows into table.
"""
input ShootImage_Data {
  """
  ✨ Generated from Field `ShootImage`.`shootId` of type `UUID!`
  """
  shootId: UUID
  """
  ✨ `_expr` server value variant of `shootId` (✨ Generated from Field `ShootImage`.`shootId` of type `UUID!`)
  """
  shootId_expr: UUID_Expr
  """
  ✨ Generated from Field `ShootImage`.`imageId` of type `UUID!`
  """
  imageId: UUID
  """
  ✨ `_expr` server value variant of `imageId` (✨ Generated from Field `ShootImage`.`imageId` of type `UUID!`)
  """
  imageId_expr: UUID_Expr
  """
  ✨ Generated from Field `ShootImage`.`image` of type `Image!`
  """
  image: Image_Key
  """
  ✨ Generated from Field `ShootImage`.`shoot` of type `Shoot!`
  """
  shoot: Shoot_Key
  """
  ✨ Generated from Field `ShootImage`.`isVisible` of type `Boolean!`
  """
  isVisible: Boolean
  """
  ✨ `_expr` server value variant of `isVisible` (✨ Generated from Field `ShootImage`.`isVisible` of type `Boolean!`)
  """
  isVisible_expr: Boolean_Expr
  """
  ✨ Generated from Field `ShootImage`.`order` of type `Int!`
  """
  order: Int
  """
  ✨ `_expr` server value variant of `order` (✨ Generated from Field `ShootImage`.`order` of type `Int!`)
  """
  order_expr: Int_Expr
  """
  ✨ `_update` server value variant of `order` (✨ Generated from Field `ShootImage`.`order` of type `Int!`)
  """
  order_update: [Int_Update!]
}
"""
✨ Generated filter input type for table 'ShootImage'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input ShootImage_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [ShootImage_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: ShootImage_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [ShootImage_Filter!]
  """
  ✨ Generated from Field `ShootImage`.`shootId` of type `UUID!`
  """
  shootId: UUID_Filter
  """
  ✨ Generated from Field `ShootImage`.`imageId` of type `UUID!`
  """
  imageId: UUID_Filter
  """
  ✨ Generated from Field `ShootImage`.`image` of type `Image!`
  """
  image: Image_Filter
  """
  ✨ Generated from Field `ShootImage`.`shoot` of type `Shoot!`
  """
  shoot: Shoot_Filter
  """
  ✨ Generated from Field `ShootImage`.`isVisible` of type `Boolean!`
  """
  isVisible: Boolean_Filter
  """
  ✨ Generated from Field `ShootImage`.`order` of type `Int!`
  """
  order: Int_Filter
}
"""
✨ Generated first-row input type for table 'ShootImage'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input ShootImage_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [ShootImage_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: ShootImage_Filter
}
"""
✨ Generated having input type for table 'ShootImage'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input ShootImage_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [ShootImage_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: ShootImage_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [ShootImage_Having!]
  """
  ✨ Generated from Field `ShootImage`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `ShootImage`.`imageId_count` of type `Int!`
  """
  imageId_count: Int_Filter
  """
  ✨ Generated from Field `ShootImage`.`isVisible_count` of type `Int!`
  """
  isVisible_count: Int_Filter
  """
  ✨ Generated from Field `ShootImage`.`order_count` of type `Int!`
  """
  order_count: Int_Filter
  """
  ✨ Generated from Field `ShootImage`.`shootId_count` of type `Int!`
  """
  shootId_count: Int_Filter
  """
  ✨ Generated from Field `ShootImage`.`order_sum` of type `Int`
  """
  order_sum: Int_Filter
  """
  ✨ Generated from Field `ShootImage`.`order_avg` of type `Float`
  """
  order_avg: Float_Filter
  """
  ✨ Generated from Field `ShootImage`.`order_min` of type `Int`
  """
  order_min: Int_Filter
  """
  ✨ Generated from Field `ShootImage`.`order_max` of type `Int`
  """
  order_max: Int_Filter
}
"""
✨ Generated key input type for table 'ShootImage'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input ShootImage_Key {
  """
  ✨ Generated from Field `ShootImage`.`shootId` of type `UUID!`
  """
  shootId: UUID
  """
  ✨ `_expr` server value variant of `shootId` (✨ Generated from Field `ShootImage`.`shootId` of type `UUID!`)
  """
  shootId_expr: UUID_Expr
  """
  ✨ Generated from Field `ShootImage`.`imageId` of type `UUID!`
  """
  imageId: UUID
  """
  ✨ `_expr` server value variant of `imageId` (✨ Generated from Field `ShootImage`.`imageId` of type `UUID!`)
  """
  imageId_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'ShootImage'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input ShootImage_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: ShootImage_Filter
}
"""
✨ Generated order input type for table 'ShootImage'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input ShootImage_Order {
  """
  ✨ Generated from Field `ShootImage`.`shootId` of type `UUID!`
  """
  shootId: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`imageId` of type `UUID!`
  """
  imageId: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`image` of type `Image!`
  """
  image: Image_Order
  """
  ✨ Generated from Field `ShootImage`.`shoot` of type `Shoot!`
  """
  shoot: Shoot_Order
  """
  ✨ Generated from Field `ShootImage`.`isVisible` of type `Boolean!`
  """
  isVisible: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`order` of type `Int!`
  """
  order: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`imageId_count` of type `Int!`
  """
  imageId_count: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`isVisible_count` of type `Int!`
  """
  isVisible_count: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`order_count` of type `Int!`
  """
  order_count: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`shootId_count` of type `Int!`
  """
  shootId_count: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`order_sum` of type `Int`
  """
  order_sum: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`order_avg` of type `Float`
  """
  order_avg: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`order_min` of type `Int`
  """
  order_min: OrderDirection
  """
  ✨ Generated from Field `ShootImage`.`order_max` of type `Int`
  """
  order_max: OrderDirection
}
"""
✨ Generated data input type for table 'User'. It includes all necessary fields for creating or upserting rows into table.
"""
input User_Data {
  """
  ✨ Generated from Field `User`.`uid` of type `String!`
  """
  uid: String
  """
  ✨ `_expr` server value variant of `uid` (✨ Generated from Field `User`.`uid` of type `String!`)
  """
  uid_expr: String_Expr
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `User`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `User`.`email` of type `String`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `User`.`email` of type `String`)
  """
  email_expr: String_Expr
}
"""
✨ Generated filter input type for table 'User'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [User_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: User_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [User_Filter!]
  """
  ✨ Generated from Field `User`.`uid` of type `String!`
  """
  uid: String_Filter
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`email` of type `String`
  """
  email: String_Filter
  """
  ✨ Generated from Field `User`.`compCards_on_user` of type `[CompCard!]!`
  """
  compCards_on_user: CompCard_ListFilter
  """
  ✨ Generated from Field `User`.`images_on_user` of type `[Image!]!`
  """
  images_on_user: Image_ListFilter
  """
  ✨ Generated from Field `User`.`portfolio_on_user` of type `Portfolio`
  """
  portfolio_on_user: Portfolio_Filter
  """
  ✨ Generated from Field `User`.`profile_on_user` of type `Profile`
  """
  profile_on_user: Profile_Filter
}
"""
✨ Generated first-row input type for table 'User'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input User_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [User_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: User_Filter
}
"""
✨ Generated having input type for table 'User'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input User_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [User_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: User_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [User_Having!]
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `User`.`uid_count` of type `Int!`
  """
  uid_count: Int_Filter
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'User'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input User_Key {
  """
  ✨ Generated from Field `User`.`uid` of type `String!`
  """
  uid: String
  """
  ✨ `_expr` server value variant of `uid` (✨ Generated from Field `User`.`uid` of type `String!`)
  """
  uid_expr: String_Expr
}
"""
✨ Generated list filter input type for table 'User'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input User_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: User_Filter
}
"""
✨ Generated order input type for table 'User'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input User_Order {
  """
  ✨ Generated from Field `User`.`uid` of type `String!`
  """
  uid: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `User`.`email` of type `String`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `User`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `User`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `User`.`uid_count` of type `Int!`
  """
  uid_count: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `User`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
