extend type Mutation {
  """
  ✨ Insert a single `CompCard` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  compCard_insert(
    """
    Data object to insert into the table.
    """
    data: CompCard_Data!
  ): CompCard_KeyOutput! @fdc_generated(from: "CompCard", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Image` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  image_insert(
    """
    Data object to insert into the table.
    """
    data: Image_Data!
  ): Image_KeyOutput! @fdc_generated(from: "Image", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Portfolio` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  portfolio_insert(
    """
    Data object to insert into the table.
    """
    data: Portfolio_Data!
  ): Portfolio_KeyOutput! @fdc_generated(from: "Portfolio", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Profile` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  profile_insert(
    """
    Data object to insert into the table.
    """
    data: Profile_Data!
  ): Profile_KeyOutput! @fdc_generated(from: "Profile", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Shoot` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  shoot_insert(
    """
    Data object to insert into the table.
    """
    data: Shoot_Data!
  ): Shoot_KeyOutput! @fdc_generated(from: "Shoot", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `ShootImage` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  shootImage_insert(
    """
    Data object to insert into the table.
    """
    data: ShootImage_Data!
  ): ShootImage_KeyOutput! @fdc_generated(from: "ShootImage", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `CompCard` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  compCard_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [CompCard_Data!]!
  ): [CompCard_KeyOutput!]! @fdc_generated(from: "CompCard", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Image` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  image_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Image_Data!]!
  ): [Image_KeyOutput!]! @fdc_generated(from: "Image", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Portfolio` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  portfolio_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Portfolio_Data!]!
  ): [Portfolio_KeyOutput!]! @fdc_generated(from: "Portfolio", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Profile` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  profile_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Profile_Data!]!
  ): [Profile_KeyOutput!]! @fdc_generated(from: "Profile", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Shoot` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  shoot_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Shoot_Data!]!
  ): [Shoot_KeyOutput!]! @fdc_generated(from: "Shoot", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `ShootImage` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  shootImage_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [ShootImage_Data!]!
  ): [ShootImage_KeyOutput!]! @fdc_generated(from: "ShootImage", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `CompCard` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CompCard`.
  """
  compCard_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: CompCard_Data!
  ): CompCard_KeyOutput! @fdc_generated(from: "CompCard", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Image` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Image`.
  """
  image_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Image_Data!
  ): Image_KeyOutput! @fdc_generated(from: "Image", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Portfolio` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Portfolio`.
  """
  portfolio_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Portfolio_Data!
  ): Portfolio_KeyOutput! @fdc_generated(from: "Portfolio", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Profile` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Profile`.
  """
  profile_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Profile_Data!
  ): Profile_KeyOutput! @fdc_generated(from: "Profile", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Shoot` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Shoot`.
  """
  shoot_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Shoot_Data!
  ): Shoot_KeyOutput! @fdc_generated(from: "Shoot", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `ShootImage` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ShootImage`.
  """
  shootImage_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: ShootImage_Data!
  ): ShootImage_KeyOutput! @fdc_generated(from: "ShootImage", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `CompCard` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `CompCard`.
  """
  compCard_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [CompCard_Data!]!
  ): [CompCard_KeyOutput!]! @fdc_generated(from: "CompCard", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Image` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Image`.
  """
  image_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Image_Data!]!
  ): [Image_KeyOutput!]! @fdc_generated(from: "Image", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Portfolio` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Portfolio`.
  """
  portfolio_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Portfolio_Data!]!
  ): [Portfolio_KeyOutput!]! @fdc_generated(from: "Portfolio", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Profile` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Profile`.
  """
  profile_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Profile_Data!]!
  ): [Profile_KeyOutput!]! @fdc_generated(from: "Profile", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Shoot` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Shoot`.
  """
  shoot_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Shoot_Data!]!
  ): [Shoot_KeyOutput!]! @fdc_generated(from: "Shoot", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `ShootImage` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `ShootImage`.
  """
  shootImage_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [ShootImage_Data!]!
  ): [ShootImage_KeyOutput!]! @fdc_generated(from: "ShootImage", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `CompCard` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `CompCard` or `null` if not found.
  """
  compCard_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CompCard_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CompCard_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: CompCard_Data!
  ): CompCard_KeyOutput @fdc_generated(from: "CompCard", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Image` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Image` or `null` if not found.
  """
  image_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Image_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Image_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Image_Data!
  ): Image_KeyOutput @fdc_generated(from: "Image", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Portfolio` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Portfolio` or `null` if not found.
  """
  portfolio_update(
    """
    The key used to identify the object.
    """
    key: Portfolio_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Portfolio_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Portfolio_Data!
  ): Portfolio_KeyOutput @fdc_generated(from: "Portfolio", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Profile` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Profile` or `null` if not found.
  """
  profile_update(
    """
    The key used to identify the object.
    """
    key: Profile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Profile_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Profile_Data!
  ): Profile_KeyOutput @fdc_generated(from: "Profile", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Shoot` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Shoot` or `null` if not found.
  """
  shoot_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Shoot_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Shoot_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Shoot_Data!
  ): Shoot_KeyOutput @fdc_generated(from: "Shoot", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `ShootImage` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `ShootImage` or `null` if not found.
  """
  shootImage_update(
    """
    The key used to identify the object.
    """
    key: ShootImage_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ShootImage_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: ShootImage_Data!
  ): ShootImage_KeyOutput @fdc_generated(from: "ShootImage", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `CompCard` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  compCard_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: CompCard_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: CompCard_Data!
  ): Int! @fdc_generated(from: "CompCard", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Image` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  image_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Image_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Image_Data!
  ): Int! @fdc_generated(from: "Image", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Portfolio` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  portfolio_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Portfolio_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Portfolio_Data!
  ): Int! @fdc_generated(from: "Portfolio", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Profile` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  profile_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Profile_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Profile_Data!
  ): Int! @fdc_generated(from: "Profile", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Shoot` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  shoot_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Shoot_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Shoot_Data!
  ): Int! @fdc_generated(from: "Shoot", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `ShootImage` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  shootImage_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: ShootImage_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: ShootImage_Data!
  ): Int! @fdc_generated(from: "ShootImage", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `CompCard` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  compCard_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CompCard_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CompCard_FirstRow
  ): CompCard_KeyOutput @fdc_generated(from: "CompCard", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Image` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  image_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Image_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Image_FirstRow
  ): Image_KeyOutput @fdc_generated(from: "Image", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Portfolio` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  portfolio_delete(
    """
    The key used to identify the object.
    """
    key: Portfolio_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Portfolio_FirstRow
  ): Portfolio_KeyOutput @fdc_generated(from: "Portfolio", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Profile` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  profile_delete(
    """
    The key used to identify the object.
    """
    key: Profile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Profile_FirstRow
  ): Profile_KeyOutput @fdc_generated(from: "Profile", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Shoot` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  shoot_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Shoot_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Shoot_FirstRow
  ): Shoot_KeyOutput @fdc_generated(from: "Shoot", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `ShootImage` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  shootImage_delete(
    """
    The key used to identify the object.
    """
    key: ShootImage_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ShootImage_FirstRow
  ): ShootImage_KeyOutput @fdc_generated(from: "ShootImage", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `CompCard` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  compCard_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: CompCard_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "CompCard", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Image` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  image_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Image_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Image", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Portfolio` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  portfolio_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Portfolio_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Portfolio", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Profile` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  profile_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Profile_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Profile", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Shoot` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  shoot_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Shoot_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Shoot", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `ShootImage` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  shootImage_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: ShootImage_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "ShootImage", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
