extend type Query {
  """
  ✨ Look up a single `CompCard` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  compCard(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: CompCard_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: CompCard_FirstRow
  ): CompCard @fdc_generated(from: "CompCard", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Image` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  image(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Image_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Image_FirstRow
  ): Image @fdc_generated(from: "Image", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Portfolio` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  portfolio(
    """
    The key used to identify the object.
    """
    key: Portfolio_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Portfolio_FirstRow
  ): Portfolio @fdc_generated(from: "Portfolio", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Profile` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  profile(
    """
    The key used to identify the object.
    """
    key: Profile_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Profile_FirstRow
  ): Profile @fdc_generated(from: "Profile", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Shoot` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  shoot(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Shoot_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Shoot_FirstRow
  ): Shoot @fdc_generated(from: "Shoot", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ShootImage` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  shootImage(
    """
    The key used to identify the object.
    """
    key: ShootImage_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ShootImage_FirstRow
  ): ShootImage @fdc_generated(from: "ShootImage", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `CompCard` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  compCards(
    """
    Filter condition to narrow down the query results.
    """
    where: CompCard_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [CompCard_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: CompCard_Having
  ): [CompCard!]! @fdc_generated(from: "CompCard", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Image` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  images(
    """
    Filter condition to narrow down the query results.
    """
    where: Image_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Image_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Image_Having
  ): [Image!]! @fdc_generated(from: "Image", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Portfolio` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  portfolios(
    """
    Filter condition to narrow down the query results.
    """
    where: Portfolio_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Portfolio_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Portfolio_Having
  ): [Portfolio!]! @fdc_generated(from: "Portfolio", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Profile` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  profiles(
    """
    Filter condition to narrow down the query results.
    """
    where: Profile_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Profile_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Profile_Having
  ): [Profile!]! @fdc_generated(from: "Profile", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Shoot` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  shoots(
    """
    Filter condition to narrow down the query results.
    """
    where: Shoot_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Shoot_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Shoot_Having
  ): [Shoot!]! @fdc_generated(from: "Shoot", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ShootImage` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  shootImages(
    """
    Filter condition to narrow down the query results.
    """
    where: ShootImage_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ShootImage_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ShootImage_Having
  ): [ShootImage!]! @fdc_generated(from: "ShootImage", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
